---
name: terraform deployment
on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
        description: 'AWS Access Key ID to install AWS CLI.'
      AWS_SECRET_ACCESS_KEY:
        required: true
        description: 'AWS Secret access key to install AWS CLI'

jobs:
  terraform-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: 'Terraform Format'
        uses: 'dflook/terraform-fmt-check@v1'
        with:
          actions_subcommand: 'fmt'
          path: './_example'

      - name: terraform init
        run: |
          cd ./_example
          terraform init

      - name: 'terraform plan'
        run: |
          cd ./_example
          terraform plan

#      - name: 'terraform apply'
#        run: |
#          cd ./_example
#          terraform apply -auto-approve
...